- benchmark
- package.json
- yarn.lock
1. why not?
2. keeping warmup cycle in mind is important
3. current benchmark is producing only one value instead of mean and stddev
> move from in-house benchmarking solution to jsperf one

- format.js
somehow speed is increased a bit (possibly, on omitting pointer allocation) and -5 bytes of output file size is gained. 
On benchmark branch commit (https://github.com/ai/nanoid/pull/11) I've got (on macbook pro 2015 i7)
```
vrodionov ~/W/nanoid> node benchmark #without this commit
nanoid#generate x 72,079 ops/sec ±1.65% (85 runs sampled)
vrodionov ~/W/nanoid> node benchmark #with this commit
nanoid#generate x 77,860 ops/sec ±0.90% (86 runs sampled)
```
> drop "byte" variable

- format.js
- package.json
Calculate `mask` directly from `alphabet.length` using log base 2 and some bitshifts
| dictionary length | mask value |
|--|--|
| 0 | 1 |
| 1 | 1 |
| 2 | 1 |
| 3 | 3 |
| 4 | 3 |
| 5 | 7 |
| 6 | 7 |
| 7 | 7 |
| 8 | 7 |
| 9 | 15 |
| _..._ | 15 |
| 16 | 15 |
| 17 | 31 |
| _..._ | 31 |
| 32 | 31 |
| 33 | 63 |
| _..._ | 63 |
| 64 | 63 |
| 65 | 127 |
| _..._ | 127 |
| 128 | 127 |
| 129 | 255 |
| _..._ | 255 |
| 256 | 255 |
> Calculate mask directly from alphabet length

- README.md
- format.js
- index.js
- test/index.test.js
Addresses Issue #33, reducing the default ID length from 22 to 21, while maintaining more random bits than UUID v4.
Additionally, I cleaned up the README a bit. Mostly grammar fixes and tweaks to make comparisons to UUID a bit more accurate.
> Reduce default ID length. Issue #33

- index.js
- package.json
There's no difference, in which direction we're traversing the array of random values: they're random.
The loop was reversed, so the size can be reused as a loop counter.
I had to temporary disable a `yoda` eslint rule for one line. The reason is, Uglify cannot minify `i-- > 0` to `i-->0` because `-->` can be parsed as [a single token](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-html-like-comments).
> 176 b: Reverse loop, reuse var

- README.md
In the example of the nanoid output was a string with 22 characters length, changed it to the correct string with length 21 characters
> Changed example of the nanoid output

- random-browser.js
Currently you are not able to use `nanoid` inside of a [Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API). This is due to `window` not being defined in [`WorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope). This PR fixes the compatibility problem by using [`self`](https://developer.mozilla.org/en-US/docs/Web/API/Window/self) instead of `window`.
> fix: use self when referencing the global scope

- README.md
Nanoid-dictionary is a set of strings to use with nanoid generator. For example you can use `filename` as a cross-platform safe character set for file name generation.
> README: Create 'See also' section and add nanoid-dictionary there

- .size-limit
- index.js
The string contains all the same characters: Alphanumeric and `~_`, but their order has changed:
For the code itself the order is not significant, but it's significant when serving a GZIPped code to the client. 
There's a very high chance words `crypto` and `getRandomValues` will be bundled somewhere near this string. And GZIP now has the opportunity to just copy the whole `getRandomV` and `cryp` string runs via backreferences (which of these "costs" only a few bits) instead of plain Huffman encoding.
Overall, this technique saves 8 .min.gz bytes - 5% of the entire entry size
> Make the chars order GZIP-friendly

- .travis.yml
Node.js 6, 8 and 10 are LTS and stable releases. The releases between them are short living branches which are not supported when an LTS release is done.
Node.js 9 reached its EOL on 30th of June
https://github.com/nodejs/Release
> chore: remove Node.js 9 from Travis CI config

- non-secure.js
Use `|` operator instead of `Math.floor()`.
Now, my name *might* be saved in history ;-)
> Use `|` operator instead of Math.floor()

- README.md
Replaced the links in readme, but there is another one in the description.
> Replace link to calculator

- non-secure.js
The `Math.random` function returns a number in the range 0–1 (inclusive of 0, but not 1), so `Math.random() * 63 | 0` will never return 63.
> Fix bug in non-secure.js

- async.js
- random.js
- test/async.test.js
Improve perfomance for nodejs version. My results:
```
nanoid                331,738 ops/sec
nanoid/generate       327,488 ops/sec
uid.sync              327,499 ops/sec
uuid/v4               321,873 ops/sec
shortid                31,894 ops/sec
Async:
uid                    61,713 ops/sec
nanoid/async           60,515 ops/sec
Non-secure:
rndm                2,310,600 ops/sec
nanoid/non-secure   2,441,124 ops/sec
```
```
nanoid                374,446 ops/sec
nanoid/generate       367,777 ops/sec
uid.sync              326,813 ops/sec
uuid/v4               322,756 ops/sec
shortid                31,409 ops/sec
Async:
uid                    62,463 ops/sec
nanoid/async           66,546 ops/sec
Non-secure:
rndm                2,323,620 ops/sec
nanoid/non-secure   2,463,917 ops/sec
```
> perf: preallocate buffers in nodejs.

- .travis.yml
- async.js
- random.js
- test/async.test.js
- test/random.test.js
Unfortunately I can't add an older Node config to the TravisCI env, because `eslint` requires `node>=6.14.0` (see the tests for the first commit)
> Restore support for Node.js<v6.13.0

- url.js
Some symbols movement for improving gzip size from 73 bytes to 70 (checked with size-limit)
> Reduce url symbols size for 3 bytes

- test/bruteforce
I've created a simple console-output-based brute-force script. It looks like a crypto mining now.
> Simple brute-force implementation

- index.js
When `typeof` is used with unresolved reference, it swallows `ReferenceError` and returns `"undefined"`. `attempt` binding is defined here, so it is safe to compare to `undefined` directly.
> Remove extra `typeof`

- package.json
- test/benchmark
- yarn.lock
secure-random-string has comparable performance for the async API despite
returning 32 characters by default, but is slower in the sync benchmark.
I tried benchmarking returning on 21 characters for a more comparable test, but
it was hardly faster.
> test: add benchmark for secure-random-string

- README.md
I added some documentation how to use nanoid with react-native when using expo. Had to search a while to find `expo-random` and to get nanoid up and running, so I thought it would be worth sharing in the documentation.
> Adds documentation for react-native using expo

- async/random.reactnative.js
- package.json
My colleagues are building a react-native application. We use `nanoid` as part of our login flow. While introducing our common solution I got an issues reported that the current usage of `nanoid` breaks the application for them. The reason for this is the exception which is being thrown in `index.browser.js`. (Interestingly the same exception should be probably added to the async layer - which is not yet implemented.) Back to the issue. We could probably think of adding [a `react-native` entry](https://github.com/facebook/metro/blob/a29d30327365f3f52652f68d53896355021cc693/packages/metro/src/node-haste/Package.js#L45) as supported by the Metro bundler (used by React Native) to use a special random number generator in async. 
For our login flow I am fine with using the async API. But still …
> Allow react-native alternative for a async random number generator

- README.md
Add the missing word "start" on "PouchDB and CouchDB" section of README
> Add missing word on README

- README.md
Hello! The working link to py-nanoid-dictionary has changed as the library is no longer available on Github.
> Updated link to py-nanoid-dictionary

- README.md
Rename repo to `nanoid-dart` to avoid confusion
https://github.com/pd4d10/nanoid-dart
> Update Dart implementation link

- async/random.rn.js
- package.json
Some small fixes for react native.
Maybe its a Windows thing, but the path for the `random.rn.js` in `package.json` should be relative to the root.
> Unable to resolve "./random" from "node_modules\nanoid\async\index.js"
Also, the call to `expo-random` was a bit off.
> [Unhandled promise rejection: TypeError: expo-random: getRandomBytesAsync(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) expected a valid number from range 0...1024]
Correct method signature is: `getRandomBytesAsync(byteCount: number): Promise<Uint8Array>`
> Fix react native usage

- index.browser.js
This isn't a huge gain, but ran across these while doing some other testing.
In the browser version while loop, I believe there is an extra comparison `0 <`. 
Also, I've found using `+=` reduces performance ~4k-6k/sec.
Showing improvements of ~10k-80k/sec (or randomly 1.5million/sec when the stars align) depending on browser (needs more testing).
`index.browser.js`
```js
// Original 
while (0 < size--) {
id += url[bytes[size] & 63]
}
// Modified
while (size--) {
id = id + url[bytes[size] & 63]
}
```
View benchmarks on jsPerf
**[64 length](https://jsperf.com/nano-id-browser-optimizations/1)**
**[21 length](https://jsperf.com/nano-id-browser-optimizations/2)**
(shorter lengths have more variance/unstable)
In the benchmarks link, I explored using modulo vs the bitwise `&` and caching the url …
> Improve performance by removing extra comparison

- package.json
Microtime is not used anywhere and breaks project scaffolding in Windows.
> chore: remove microtime dependency

- async/format.js
- format.js
- test/async-format.test.js
- test/format.test.js
>   generate.js
>   Size limit: 180 B
>   Size:       **177** B with all dependencies, minified and gzipped
>   async/generate.js
>   Size limit: 201 B
>   Size:       **199** B with all dependencies, minified and gzipped
This PR changes logic for `format` function a bit, but... This is «_random_ string generator» eventually, I guess, this change will not break, well, _randomness_.
I also have changed tests for new results.
> Reverse format for cycle

- generate.js
I'm unsure about whether you want to use .bind - but from my point of view it is pretty usable (IE9+, even more than getRandomValues reference) and somehow exactly `null` (neither `undefined` nor `0` or whatever) produces 2kb less.
> use .bind to reduce bundle 2b more

- format.js
- package.json
- replace emulated integer `log2(x)` to `31 - clz(x)` which should speed up bust formatting
- move `size = +size` before it first usage
Coveats: **+2 bytes**
> Speedup mask calculation in format

- README.md
This helps to understand how to use nanoid with react hooks.
> Adding example for react using hooks

- non-secure/index.js
- package.json
102 -> 89 (-13) bytes for `non-secure/index.js`
----
This can go down to 87 if the `url` variable is reused as `i`:
```
var url =  String.fromCharCode(
url = 48, url += 1, url += 1, ...
```
There are downsides though:
- eslint rants about a _variable is used before before it was defined_.
- This way the `url` variable changes its type from `number` to `string` in the runtime. At least V8 could JIT the code worse when it encounters a non-monomorphic variable.
> Non-secure: Generate alphabet using fromCharCode

- async/index.browser.js
- index.browser.js
- non-secure/index.js
- package.json
- url.js
Url generation based on @anber_ru's proposal.
> Reduce size by new url generation and counter reuse

- non-secure/index.js
do not reference secure js in non-secure js, since it will force the bundler to require `crypto`.
> do not reference secure js in non-secure js

- package.json
~~Since @ai mentioned we only support `^10`, `^12`, and `>=13`, I didn't include `^11`. But if there is no reason not to support `^11` (as far as I can tell it actually works), we can update the semver as `">=10 <13 || >=13.7"`.~~
Nvm, I didn't realize Node disowned `11` 😂 
Alright this fixes https://github.com/ai/nanoid/issues/215
> Restrict failing node@13.x versions at engines.node

- README.md
Adds an entry for `janet-nanoid`, a port of nanoid in the [Janet](https://janet-lang.org/) programming language.
See https://sr.ht/~statianzo/janet-nanoid/ for details
> Added janet implementation

- README.md
Put a link to C++ implementation of nanoid at the "Other Programming Languages" part of README.
> Added C++ implementation reference to README

- async/index.browser.js
To ensure consistency in the functions exported by async/browser.index
and to not catch out users expecting a Thenable returned by functions
claimed to be async, ensure that the final value returned by 
`customAlphabet()` is a Promise resolving to the value, not the value
itself
Fixes #228
> async/customAlphabet - ensure browser version returns Promise

- async/index.browser.js
- async/index.js
- async/index.native.js
- index.browser.js
- index.js
We want to return the id when the length of the id equals the desired size.
This fixes the annotation as it is not changing the outcome; The plus doesn't change the expression `1 === +1 // true`.
> Fix custom random return condition

- README.md
I have an React component library, which is bundled with Rollup. Then this library is used with app bundled with webpack. After importing `nanoid` in this library and bundling with Rollup. Webpack then adds 590.15kb of Node.js polyfill to the bundle.
The reason is Rollup bundles `index.js`, which has `import crypto from 'crypto'`. When I configure Rollup `node-resolve` plugin to search for `browser` field, then `index.browser.js` imported into bundle.
I thought update of documentation could help other developers.
> Improve Rollup usage documentation

- README.md
HTML5 lifted the restrictions on `id` values, which are now essentially any character sequence: https://mathiasbynens.be/notes/html5-id-class
This was specced about 11 years ago and made with HTML ≤4.01 backwards compatibility in mind. It should be safe to no longer worry about this.
> Remove HTML `id` advice

- README.md
- README.ru.md
- README.zh-CN.md
Completely removed notes about HTML id usage. "HTML ID" anchor was broken in EN docs since this section was deleted in https://github.com/ai/nanoid/pull/316.
> docs: remove notes about HTML id usage

- README.md
Our implementation was just merged in the main OCaml package repository.
Thank for Nano IDs!
> Document the existence of the OCaml port.

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
Hi!
Thanks for making this library. It's super simple, fast, and very useful for my use-cases!
If you don't mind, I have translated and added `README.id-ID.md` for internationalization purposes (I'm from Indonesia). The documentation now has four languages: English, Russian, Chinese, and Bahasa Indonesia 🎉
By the way, I have a question about a single statement in `async` part of the documentation:
> Unfortunately, you will lose Web Crypto API advantages in a browser if you use the asynchronous API. So, currently, in the browser, you are limited with either security or asynchronous behavior.
The 'security' part here is a bit confusing for me. So, in order to remove any ambiguity, I think it's better if we rewrite this to be like:
> Unfortunately, you will lose Web Crypto API advantages in …
> Add documentation in Bahasa Indonesia

- index.js
- test/index.test.js
You can test live reproduce here https://stackblitz.com/edit/nanoid-collision?file=index.js (type `node index.js` in the console)
> fix collision by proxy number

- CHANGELOG.md
Due to a small Typo in changelog, the version details were not fetched correctly by `renovate`.
Have fixed the same.
> doc: Fixed Typo in changelog.md

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
I have created and I maintain the [NanoID](https://github.com/MichelBoucey/NanoID), library and cli tool, which can be found on Haskell Community website, [Hackage](https://hackage.haskell.org/package/NanoID). That's why I suggest, with this PR, to replace the current Haskell implementation, which has a pure educational purposes, according to the author himself, by my implementation, built idiomatically the Haskell way.
> Switch Haskell NanoID implementation to the Community maintained one

- bin/nanoid.cjs
I think @vitalybaev made a mistake ([/bin/nanoid.cjs#L19](https://github.com/ai/nanoid/blob/32b9bdaab1fbc28576b17de8516164ce0360f292/bin/nanoid.cjs#L19))
> fix: CLI help examples

- README.md
- README.ru.md
- README.zh-CN.md
In #355 improvement with reduce was introduced. However, it relies on the fact, that `UInt8Array` is really an array, but in IE actually it's not. Today I investigated it, and it turned out, that `UInt8Array` in `msCrypto` is an object.
I found the following workaround, but I'm not sure is there any problems with it. If it's OK, I'll update Russian readme as well.
> Update IE polyfill to fix last improve with reduce

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
I created a newer and improved Go implementation of nanoid ([link](https://github.com/jaevor/go-nanoid)) and I wanted to update the links in the reference repo 🙂.
> docs: new link to Go implementation

- README.md
Hello, it might be helpful to some users to mention the new `useId` hook from React 18 as a simple alternative to nanoid for html attributes.
Cheers
> Add small section on using built in useId-hook in newer React versions

- README.md
Simple README.md change to draw attention to the fact that customAlphabet returns a function.
> "returns a function that"

- package.json
In the package.json, `./async/index.browser.cjs`  does not exist.
> fix: file doesn't exist

- README.md
https://github.com/jaevor/go-nanoid license was changed to GPL. Recommend an alternate implementation.
> docs: update Go library to atoous/go-nanoid

- async/index.native.js
Removes usage of the now deprecated `expo-random`. Closes #414
> Replace deprecated `expo-random` package

- README.zh-CN.md
> docs: update chinese doc

- index.js
- package.json
Using `crypto.webcrypto.getRandomValues()` is recommended instead of directly using the aliased version from `crypto.getRandomValues()` as the latter is not meant to be compatible with the WebCrypto spec and is non-standard. 
There was earlier discussion on this in the node repo - https://github.com/nodejs/node/pull/41779, https://github.com/nodejs/node/pull/41782,  https://github.com/nodejs/node/pull/41760
This is breaking some downstream tools as well that are bundling / down-compiling nanoid (although that's not much of an nanoid issue).
PS: updating the `clean` script as well. Running `test` was failing for new contributors who don't already have a coverage directory.
> fix(node): use webcrypto export from `node:crypto`

- bin/nanoid.js
Fix command-line usage example: `nanoid --s 15` -> `nanoid -s 15`
> Fix command-line usage example.

- bin/nanoid.js
Removed empty line and two spaces on every line in --help cli message
> Fixed formating for cli --help message

- index.browser.js
- nanoid.js
- package.json
I know this is a lazy PR since I didn't check other files to make sure I'm making the correct changes, so I'm sorry about that.
This implementation is much faster.
The benchmark checks the time to generate one million nanoids.
```
$ node ./main.js
Old 1365ms
New 948ms
$ bun ./main.js
Old 462ms
New 138ms
```
I hope you find it useful 🙏
> Much faster implementation

- .gitignore
- index.browser.js
- index.js
This proposed the fix of [problem](https://github.com/ai/nanoid/issues/470)
> add scoped name of urlAlphabet which is in export and import in one file

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
Hey,
A while back I forked the original Java nanoid library (jnanoid), since optimizations and improvements could be made:
- Security Issue: Remote code execution could be ran.
- Random Security: Java's more secure Random wasn't being used.
- Better Unit Testing
- More useful methods
In the readme the recommended Java Library is still pointing to the discontinued one. I've updated it.
> Update java library

- README.md
The original python implementation ([py-nanoid](https://github.com/puyuan/py-nanoid)) is unmaintained by the author and no-one else is able to merge contributions. (see: [2 year old PRs going un-acknowledged](https://github.com/puyuan/py-nanoid/pull/24#issuecomment-1019324237))
A new nanoid python library has been written in Rust ([fastnanoid](https://github.com/oliverlambson/fastnanoid)) and is 2.7x faster than the native python implementation.
> chore(readme): Add python fastnanoid

- index.browser.js
I have noticed that this line in `index.browser.js`:
```js
let mask = (2 << (Math.log(alphabet.length - 1) / Math.LN2)) - 1
```
uses `Math.log() / Math.LN2` to get the `log2`,
while it can be made shorter by using widely available `Math.log2` method:
```js
let mask = (2 << Math.log2(alphabet.length - 1)) - 1
```
How did I notice it?
Because there's an eslint rule that recommends that: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-modern-math-apis.md#prefer-mathlog2x-over
`Math.log2` seems to be widely available in the Browsers and I see no reason why it shouldn't be used.
> use `Math.log2` instead of `Math.log / Math.LN2`

- index.browser.js
- index.js
- non-secure/index.js
- test/index.test.js
When nanoid is called with a fractional value, there were a number of undesirable effects:
- in browser and non-secure, the code infinite loops on `while (size--)`
- in node, the value of poolOffset becomes fractional, causing calls to nanoid to return zeroes until the pool is next filled: when `i` is initialized to `poolOffset`, `pool[i] & 63` -> `undefined & 63` -> `0`
- if the first call in node is a fractional argument, the initial buffer allocation fails with an error
I chose `|0` to cast to a signed integer primarily because that has a slightly better outcome in the third case above: if the first call is negative (e.g. `nanoid(-1)`) then Node will throw an error for an invalid Buffer size, rather than attempting to allocate a buffer of size `2**32-1`. It's also more compact than …
> Fix pool pollution, infinite loop

- index.browser.js
- index.js
- test/index.test.js
- test/non-secure.test.js
I didn't fully understand the project and test structure, but while preparing the backport for v3 I gained a fuller understanding.
The tests now exercise the customAlphabet code and the non-secure variant, and fix the infinite loop case in `customRandom` on both node and the browser.
> Additional fixes and tests for #508

- README.md
Andrey!
I've ported Nano ID to C. See: <https://github.com/lukateras/nanoid.h>
The core [`nanoid.h`](https://github.com/lukateras/nanoid.h/blob/aab8a10e015c24a3c4682fda22eeff5a43a9544a/nanoid.h) is, much like `nanoid.js`, made as compact as possible and currently sits at 270 bytes. There's more cruft in C, types and headers and allocations and all, so it's a bit bulkier than the original, but still retains the same spirit (:
The README likewise follows the same design and structure as yours. There are also man pages, a command line interface, and a build system; all batteries included.
Передаю привет из одной испаноязычной страны в другую ^^
> Add a C port to the README

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
I'm the maintainer of jnanoid-enhanced. I originally opened a PR for this change a while back, but I've migrated the repo to another org.
> chore(readme): updated java library link

- README.id-ID.md
- README.md
- README.ru.md
- README.zh-CN.md
- index.d.ts
The PR introduces generics to the Nano ID functions that return `string`.
Right now, when using opaque (branded) strings, you have cast explicitly, which opens room for an error:
```ts
export function newWorkbenchDatasetSelect(): Workbench.CellDatasetSelect {
return {
type: "select",
id: nanoid(),
//=> Type 'string' is not assignable to type 'CellDatasetId'.
datasetUid: undefined,
selection: newDatasetSelectionSolo(),
};
}
```
Before the only option was to use `as`:
```ts
export function newWorkbenchDatasetSelect(): Workbench.CellDatasetSelect {
return {
type: "select",
id: nanoid() as Workbench.CellDatasetId,
datasetUid: undefined,
selection: newDatasetSelectionSolo(),
};
}
```
After the change, in most cases, the code won't require casting at all, as TypeScript will infer it …
> Make functions generic so it can cast to opaque (branded) types
